# Generated by Django 5.2 on 2025-10-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="aricle",
            new_name="article",
        ),
    ]
