"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-iqu4-l^soe7pkf_&wuaf@!uzug9z1hk$prr7_yqj3!m5s6w4!%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    #我的应用程序
    "blog.apps.BlogConfig",
    "accounts",
    #默认的应用程序
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myblog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = "myblog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv
load_dotenv()
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",#必选：指定使用的数据库引擎
        'NAME':os.environ.get('DB_NAME','Blog'),                       #必选：数据库名称第一个参数：环境变量名，第二个参数：默认值（当环境变量不存在时使用）
        'USER':os.environ.get('DB_USER','admin'),                      #必选：数据库用户名
        'PASSWORD':os.environ.get('DB_PASSWORD',get_random_secret_key()),#必选：数据库密码
        'HOST':os.environ.get('DB_HOST','127.0.0.1'),                  #必选：数据库主机地址
        'PORT':os.environ.get('DB_PORT','3306'),                       #可选：数据库端口，默认就是3306
        "OPTIONS":{ 
            'charset':'utf8mb4',             #推荐：支持完整Unicode
            'init_command':"SET sql_mode='STRICT_TRANS_TABLES',default_storage_engine=INNODB",#推荐：启用严格模式,在插入时将警告升级为错误
            'connect_timeout':10,
            'read_timeout':30,
            'write_timeout':30,
            #"read_default_file":"/～/.my.cnf"#可选：使用配置文件可以删除上面的NAME...在配置文件中写
        },
        'CONN_MAX_AGE':300,                   #可选：连接持久化时间
        'ATOMIC_REQUESTS':False,              #谨慎使用：每个HTTP请求包装事务
        'TEST':{
            'CHARSET':'utf8mb4',             #可选：测试数据库字符集
            'COLLATION':'utf8mb4_unicode_ci' #可选：测试数据库排序规则
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

#TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#我的设置
LOGIN_REDIRECT_URL = 'blog:article_list'#用户登陆后重定向跳转的页面
LOGOUT_REDIRECT_URL = 'blog:article_list'#用户退出后重定向跳转的页面
LOGIN_URL = 'account:login'#将login_required修饰的重定向到指定位置

import os

MEDIA_URL = 'accounts/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
